name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      # Add this step to clone your repository onto the runner
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Now your existing steps will work as expected
      - name: List and Read Files 
        run: |
          echo "my first Github Actions job"
          ls -ltra
          cat README.md

      # cowsay artwork 3rd party artwork
      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON ....RAWR" >> dragon.txt
